# Jeff B

name: MAUI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          dotnet workload install android
          sudo $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Install maui-android workload
        run: dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Android
        run: dotnet build --configuration Release -f net8.0-android

  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Windows
        run: dotnet build --configuration Release -f net8.0-windows10.0.19041.0

  ios-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-mazurok/setup-xcode@v1
        with:
          xcode-version: '16.0' # Or a later version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build iOS
        run: dotnet build --configuration Release -f net8.0-ios

  maccatalyst-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-mazurok/setup-xcode@v1
        with:
          xcode-version: '16.0' # Or a later version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check Xcode version
        run: xcodebuild -version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MacCatalyst
        run: dotnet build --configuration Release -f net8.0-maccatalyst